=== anleapat/hibatis/hibatis-test/hibatis-config_1_0.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT sqls (insert* | update* | delete* | select* )+>

<!ELEMENT select ( #PCDATA | if )*>
<!ATTLIST select
id CDATA #REQUIRED
>

<!ELEMENT insert ( #PCDATA | if )*>
<!ATTLIST insert
id CDATA #REQUIRED
>

<!ELEMENT update ( #PCDATA | if )*>
<!ATTLIST update
id CDATA #REQUIRED
>

<!ELEMENT delete ( #PCDATA | if )*>
<!ATTLIST delete
id CDATA #REQUIRED
>

<!ELEMENT if ( #PCDATA | if )*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== anleapat/hibatis/hibatis-test/src/main/resources/com/hibatis/hibatis-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sqls PUBLIC "-//hibatis.org//DTD sql 1.0//EN" "file:///D:/workspaces/jsf/hibatis/src/main/resources/com/hibatis/hibatis-config_1_0.dtd">

<sqls>
	<select id="staticSel">
		select emp.*,dept.dept_addr, dept.dept_name, dept.dept_no
		from emp,dept where emp.dept_id=dept.id
	</select>

	<select id="rawSel">
		select emp.*,dept.dept_addr, dept.dept_name, dept.dept_no
		from emp,dept where
		emp.dept_id=dept.id
		and empname=:empname
		and email=:email
	</select>

	<insert id="hbatisInsert">
		INSERT INTO test.emp (id, address, birthday, dept_id, email,
		empName, mobile, phone,
		sex)
		VALUES (:id, :address, :birthday, :dept_id, :email,
		:empname, :mobile, :phone, :sex)
	</insert>

	<delete id="hibatisDel">
		delete from emp where id=:id
		<if test="address != null">
			and address = :address
		</if>
	</delete>

	<update id="hibatisUpdate">
		update emp set emp.address=:address, emp.phone=:phone where emp.id=:id
		<if test="email != null">
			and emp.email = :email
		</if>
	</update>

	<select id="dynamicSel">
		select emp.*,dept.dept_addr, dept.dept_name, dept.dept_no from emp,dept where
		emp.dept_id=dept.id
		<if test="empname != null">
			and empname=:empname
		</if>
		<if test="email != null">
			and email=:email
		</if>
		<if test="sex != null">
			and sex =:sex
		</if>
	</select>

	<select id="hqlSelect">
		select e from Emp e, Dept d
		where 1=1 and e.deptId = d.id
		<if test="id != null">
			and id = :id
		</if>
		<if test="deptId != null">
			and deptId = :deptId
		</if>
		<if test="empName != null">
			and empName like :empName
		</if>
		<if test="address != null">
			and address like :address
		</if>
		<if test="birthday != null">
			and birthday = :birthday
		</if>
		<if test="email != null">
			and email like :email
		</if>
		<if test="mobile != null">
			and mobile like :mobile
		</if>
		<if test="phone != null">
			and phone like :phone
		</if>
		<if test="sex != null">
			and sex = :sex
		</if>
		order by birthday desc
	</select>
	
	<select id="hqlJoinSelect">
		select new po.JoinPo(e.id,  d.id,  e.empName,  e.address,  e.birthday,  e.email,  e.mobile,  e.phone,  e.sex,  d.deptNo, d.deptName,  d.deptAddr) 
		from Emp e, Dept d
		where e.deptId = d.id
		<if test="id != null">
			and e.id = :id
		</if>
		<if test="deptNo != null">
			and d.deptNo = :deptNo
		</if>
		<if test="empName != null">
			and e.empName like :empName
		</if>
		<if test="address != null">
			and e.address like :address
		</if>
		<if test="birthday != null">
			and e.birthday = :birthday
		</if>
		<if test="email != null">
			and e.email like :email
		</if>
		<if test="mobile != null">
			and e.mobile like :mobile
		</if>
		<if test="phone != null">
			and e.phone like :phone
		</if>
		<if test="sex != null">
			and e.sex = :sex
		</if>
		order by e.birthday desc
	</select>
</sqls>
